### ISSUE TITLE
reject is not defined

### ISSUE THREAD

**Issue by AndreasNasman** [Samsung/vscode-extension-tizentv#19]
I receive a **reject is not defined** error whenever I try to launch a tv application.
![image](https://user-images.githubusercontent.com/17124245/100331459-de108c80-2fd8-11eb-9e4b-05414e399be0.png)

I'm running on macOS Big Sur version 11.0.1. I took a look in the plugin directory and suspect it's something wrong with jQuery.

**Comment by prozanne** [comment]
Hi, sorry for inconvenience.
Could you please retry with the latest version(v1.2.4)?
When I try to reproduce the issue, but it seems to work well on macOS Big Sur version now.

Please retry it.

**Comment by Yria** [comment]
Same Issue.
tizentv 
v1.2.4
macOS Monterey arm64

**Comment by moreli** [comment]
Hello, any update on this? I'm having the same issue on Mac big sure 11.6.1
What logs are needed?
<img width="273" alt="Screen Shot 2021-12-31 at 9 31 50 PM" src="https://user-images.githubusercontent.com/260238/147844061-487a13a8-8487-44c2-b7a8-f27668f31cba.png">

this is the log
`[2021-12-31 21:36:28.755] [exthost] [info] Extension host with pid 22282 started
[2021-12-31 21:36:28.755] [exthost] [info] Skipping acquiring lock for /Library/Application Support/Code/User/workspaceStorage/35fa8727d329bca3cee7cfc7c75e8bbf.
[2021-12-31 21:36:28.813] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2021-12-31 21:36:28.826] [exthost] [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
[2021-12-31 21:36:28.841] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2021-12-31 21:36:28.844] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.github
[2021-12-31 21:36:28.849] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: true, activationEvent: '*', root cause: platformio.platformio-ide
[2021-12-31 21:36:29.052] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2021-12-31 21:36:29.073] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2021-12-31 21:36:29.079] [exthost] [info] ExtensionService#_doActivateExtension platformio.platformio-ide, startup: true, activationEvent: '*'
[2021-12-31 21:36:29.787] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2021-12-31 21:36:30.049] [exthost] [info] Eager extensions activated
[2021-12-31 21:36:30.065] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2021-12-31 21:36:30.072] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2021-12-31 21:36:33.844] [exthost] [info] ExtensionService#_doActivateExtension tizensdk.tizentv, startup: false, activationEvent: 'onCommand:tizentv.launchApplication'
[2021-12-31 21:36:36.863] [exthost] [error] ReferenceError: reject is not defined
	at AppLauncher.pushWgt /.vscode/extensions/tizensdk.tizentv-1.2.4/node_modules/@tizentv/webide-common-tizentv/lib/appLauncher.js:82:13)
	at async TVWebApp.launchOnTV (/.vscode/extensions/tizensdk.tizentv-1.2.4/node_modules/@tizentv/webide-common-tizentv/lib/projectHelper.js:214:13)
	at async launchApplication (/.vscode/extensions/tizensdk.tizentv-1.2.4/lib/launchApplication.js:59:13)
	at async r._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31072) tizentv.launchApplication {"value":"tizensdk.tizentv","_lower":"tizensdk.tizentv"}
`

**Comment by SejoongDeJang** [comment]
@Yria @moreli Sorry to inconvenience. 
We didn't support a launch feature with the `launch.json`. Our implement was wrong. We had removed the launch feature because of confusion.

So you can run a tizen application through a `Tizen TV: Launch Application` command.
Or you can run inspector with a `Tizen TV: Debug Application` command after that you'll have followed on your browser.

**Comment by matteo-bombelli-deltatre** [comment]
still same error when launched with command palette

![image](https://user-images.githubusercontent.com/88826036/197835743-6cf96048-91ec-4fad-9b32-3e12af29baa3.png)

**Comment by asaitov** [comment]
You need to build a signed .wgt package before launching/debugging. Otherwise it fails due to a bug in [dependency library](https://github.com/Samsung/webIDE-common-tizentv/issues/39).
